### ISSUE TITLE
[Suggestion] Add tag list to output of getSkins

### ISSUE THREAD

**Issue by Til-Weimann** [MrZillaGold/NameMCWrapper#80]

**Comment by MrZillaGold** [comment]
Loading a list of tags for each skin will take too long, I will make a separate method for loading information about the desired skin.

**Comment by MrZillaGold** [comment]
[Method](https://github.com/MrZillaGold/NameMCWrapper/blob/master/docs/EN.md#getSkin) has been implemented and will be available in the next release.

**Comment by MrZillaGold** [comment]
https://github.com/MrZillaGold/NameMCWrapper/releases/tag/1.8.0
